package com.trading.marketsignalengine.application.domain.model;

public enum SignalType {
    DATA_TRADABLE,
    NO_TRADE_OUT_OF_SYNC,
    NO_TRADE_RECOVERING_BOOK,
    NO_TRADE_STALE_BBO,
    NO_TRADE_STALE_BOOK,
    NO_TRADE_STALE_TRADES,
    NO_TRADE_INCOMPLETE_BOOK,
    SPREAD_ACCEPTABLE,
    SPREAD_TOO_WIDE,
    BUY_PRESSURE,
    SELL_PRESSURE,
    TRADE_FLOW_NEUTRAL,
    ORDER_BOOK_BULLISH,
    ORDER_BOOK_BEARISH,
    ORDER_BOOK_NEUTRAL,
    VOLATILITY_NORMAL,
    VOLATILITY_HIGH,
    REGIME_TRENDING_UP,
    REGIME_TRENDING_DOWN,
    REGIME_RANGING,
    LONG_SETUP_FORMING,
    SHORT_SETUP_FORMING,
    MARKET_MIXED,
    NO_TRADE_CONDITION
}
