[versions]
springBoot = "3.3.5"
springDependencyManagement = "1.1.6"
slf4j = "2.0.16"
jakartaValidation = "3.1.0"
junitJupiter = "5.11.3"
junitPlatformLauncher = "1.11.3"
lombok = "1.18.34"
testcontainers = "1.20.4"
confluent = "7.7.0"

[libraries]
springBom = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "springBoot" }

slf4jApi = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
jakartaValidationApi = { module = "jakarta.validation:jakarta.validation-api", version.ref = "jakartaValidation" }

junitJupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junitJupiter" }
junitPlatformLauncher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junitPlatformLauncher" }

lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }

springBootStarter = { module = "org.springframework.boot:spring-boot-starter" }
springBootStarterActuator = { module = "org.springframework.boot:spring-boot-starter-actuator" }
springBootStarterValidation = { module = "org.springframework.boot:spring-boot-starter-validation" }
springBootStarterTest = { module = "org.springframework.boot:spring-boot-starter-test" }

schemas = { module = "com.trading:trading-schemas", version = "1.0.0-SNAPSHOT" }
common = { module = "com.trading:trading-common", version = "1.0.0-SNAPSHOT" }
kafkaAvroSerializer = { module = "io.confluent:kafka-avro-serializer", version.ref = "confluent" }

testcontainersBom = { module = "org.testcontainers:testcontainers-bom", version.ref = "testcontainers" }
testcontainersJunit = { module = "org.testcontainers:junit-jupiter" }
testcontainersKafka = { module = "org.testcontainers:kafka" }

[plugins]
springBoot = { id = "org.springframework.boot", version.ref = "springBoot" }
springDependencyManagement = { id = "io.spring.dependency-management", version.ref = "springDependencyManagement" }
